name: PR Approval Check

on:
  workflow_run:
    workflows: ["Receive PR 2"]
    types: ["completed"]

permissions:
  pull-requests: read
  actions: read
  # checks: write  # (optional) if you want to create check runs

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - id: get-pr
        name: Extract PR from workflow_run payload or Github REST API
        uses: actions/github-script@v7
        with:
          script: |
            const wr = context.payload.workflow_run;
            const first = (wr.pull_requests || [])[0];

            let prNumber = first?.number ?? null;
            const owner = context.payload.workflow_run.repository.owner.login
            const headRepo = first?.head?.repo?.name ?? wr.head_repository?.name;
            const headSha = wr.head_sha;

            core.setOutput('owner', owner ?? '');
            core.setOutput('head_repo', headRepo ?? '');
            core.setOutput('head_sha', headSha ?? '');

      - name: Download artifact from triggering run
        uses: actions/download-artifact@v6
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: prnum
          path: prnum.txt
          # github-token: ${{ github.token }}

      - name: Read inputs
        id: get-pr
        run: |
          echo "pr=$(<prnum.txt)" >> "$GITHUB_OUTPUT"

      - name: Mint installation token
        id: app-token
        uses: actions/create-github-app-token@v2.1.4
        with:
          app-id: ${{ secrets.PR_APPROVAL_CHECK_APP_ID }}
          private-key: ${{ secrets.PR_APPROVAL_CHECK }}

      - name: Require Product Eng approval
        uses: trufflesecurity/pr-approval-check@workflow-triggered
        with:
          org: trufflejw
          approver_team: jeffteam
          owner: ${{ steps.get-pr.outputs.owner }}
          repo: ${{ steps.get-pr.outputs.head_repo }}
          head: ${{ steps.get-pr.outputs.head_sha }}
          number: ${{ steps.get-pr.outputs.pr_number }}
          github_token: ${{ steps.app-token.outputs.token }}


