name: PR Approval Check

on:
  workflow_run:
    workflows: ["Receive PR 2"]
    types: ["completed"]

permissions:
  pull-requests: read
  actions: read
  # checks: write  # (optional) if you want to create check runs

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - id: get-pr
        name: Extract PR from workflow_run payload or Github REST API
        uses: actions/github-script@v7
        with:
          script: |
            console.log("CONTEXT", context)
            console.log("====")
            const wr = context.payload.workflow_run;
            const first = (wr.pull_requests || [])[0];

            let prNumber = first?.number ?? null;
            const owner = context.payload.workflow_run.repository.owner.login
            const headSha = wr.head_sha;
            const headBranch = first?.head?.ref ?? wr.head_branch;
            const headRepo = first?.head?.repo?.name ?? wr.head_repository?.name;

            console.log("head_repository.full_name:", context.payload.workflow_run.head_repository.full_name);
            console.log("repository.full_name:", context.payload.workflow_run.repository.full_name);

            console.error("context", context);
            // console.error("REPOSITORY", context.payload.workflow_run.repository);
            // console.error("HEAD_COMMIT", context.payload.workflow_run.head_commit);

            if (!prNumber) {
              // console.log("owner:", context.payload.workflow_run.head_repository.owner.login)
              // console.log("reponame:", context.payload.workflow_run.head_repository.name)
              // console.log("headsha:", headSha)
              // Fallback: map commit → PR(s)
              const res = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.payload.workflow_run.head_repository.owner.login,
                repo: context.payload.workflow_run.head_repository.name,
                commit_sha: headSha,
              });
              prNumber = res.data[0]?.number ?? null;
            }
            console.log("pr_number:", prNumber);
            core.setOutput('pr_number', prNumber ?? '');
            core.setOutput('head_sha', headSha ?? '');
            core.setOutput('head_branch', headBranch ?? '');
            core.setOutput('head_repo', headRepo ?? '');
            core.setOutput('owner', owner ?? '');

      - name: Mint installation token
        id: app-token
        uses: actions/create-github-app-token@v2.1.4
        with:
          app-id: ${{ secrets.PR_APPROVAL_CHECK_APP_ID }}
          private-key: ${{ secrets.PR_APPROVAL_CHECK }}

      - name: Require Product Eng approval
        uses: trufflesecurity/pr-approval-check@workflow-triggered
        with:
          org: trufflejw
          approver_team: jeffteam
          owner: ${{ steps.get-pr.outputs.owner }}
          repo: ${{ steps.get-pr.outputs.head_repo }}
          head: ${{ steps.get-pr.outputs.head_sha }}
          number: ${{ steps.get-pr.outputs.pr_number }}
          github_token: ${{ steps.app-token.outputs.token }}


