name: PR Approval Check
on:
  pull_request_review:
    types: [submitted, dismissed]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  request-team-review:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write
    steps:
      - name: Request team review
        uses: actions/github-script@v7
        env:
          org: trufflejw
          team: jeffteam
        with:
          github-token: ${{ secrets.GH_REVIEW_TOKEN }}
          # github-token: ${{ secrets.GH_APP_TOKEN }}
          script: &runscript |
            const {org, team} = process.env
            const prettyTeamName = `@${org}/${team}`

            const children = await github.rest.teams.listChildInOrg({
                  org: org,
                  team_slug: team,
                });

            async function status(state, msg) {
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.payload.pull_request.head.sha,
                state: state,
                context: `product-eng-approval-${team}`,
                description: msg,
              });
            }

            async function fail(msg) {
              core.setFailed(msg);
              console.error(msg)
              await status('failure', msg)
              process.exit(1);
            }

            async function succeed(msg) {
              core.setOutput(msg);
              console.info(msg)
              await status('success', msg)
              process.exit(0);
            }

            await status('pending', `Waiting for approval from ${prettyTeamName} team member`)

            let reviews = {};
            try {
              const iter = octokit.paginate.iterator(github.rest.pulls.listReviews, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });
              let pages = [];
              for await (const p of iter) {
                pages.push(p)
              }

              // latestReview returns the more recently submitted of 2 reviews
              const latestReview = (a, b) => new Date(a.submitted_at) > new Date(b.submitted_at) ? a : b;

              for await (const page of iter) {
                console.log("PAGE", page)
                for (const review of page) {
                  console.log("REVIEW", review)
                  const login = review.user.login
                  reviews[login] = (login in reviews) ? latestReview(reviews[login], review) : review
                }
              }
            } catch (error) {
              await fail(`⚠️ Could not get reviews: ${error.status}`);
            }

            console.log("REVIEWERS", reviews)

            for (const login in reviews) {
              if (reviews[login].state !== 'APPROVED') {
                continue
              }
              try {
                const membership = await github.rest.teams.getMembershipForUserInOrg({
                  org: org,
                  team_slug: team,
                  username: reviewer,
                });

                if (membership.data.state == 'active') {
                  await succeed(`✅ Approved by ${reviewer} on behalf of ${prettyTeamName}`)
                }
              } catch (error) {
                if (error != 404) {
                  await fail(`⚠️ Could not determine membership for ${reviewer} in ${prettyTeamName}: ${error}`)
                }
              }
            }

            await fail(`⚠️ No approvers found from ${prettyTeamName}`)

      - name: Request team review
        uses: actions/github-script@v7
        env:
          org: trufflejw
          team: childteam
        with:
          github-token: ${{ secrets.GH_REVIEW_TOKEN }}
          script: *runscript
