name: PR Approval Check 2

on:
  workflow_run:
    workflows: ["Receive PR 2"]
    types: ["completed"]

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Mint installation token
        id: app-token
        uses: actions/create-github-app-token@v2.1.4
        with:
          app-id: ${{ secrets.PR_APPROVAL_CHECK_APP_ID }}
          private-key: ${{ secrets.PR_APPROVAL_CHECK }}

      - name: Require Product Eng approval
        uses: trufflesecurity/pr-approval-check@workflow-triggered
        with:
          org: trufflejw
          approver_team: jeffteam
          owner: ${{ github.event.pull_requests[0].head.repo.owner }}
          repo: ${{ github.event.pull_requests[0].head.repo.full_name }}
          head: ${{ github.event.pull_requests[0].head.sha }}
          number: ${{ github.event.pull_requests[0].number }}
          github_token: ${{ steps.app-token.outputs.token }}


