name: "Receive PR"

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]

permissions:
  contents: read

jobs:
  noop:
    name: Baseline check
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the required check."

