name: PR Approval Check

on:
  pull_request_review:
    types: [submitted, dismissed]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
