name: Recieve PR

on:
  pull_request_review:
    types: [submitted, dismissed]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  noop:
    name: Baseline check
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the required check."

