name: "Receive PR 2"

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  prnum:
    name: Determine and Dispatch PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - name: Set pending status
        uses: actions/github-script@v7
        with:
          script: |
            console.log("context.repo.owner:", context.repo.owner)
            console.log("context.repo.repo:", context.repo.repo)
            console.log("context.sha:", context.sha)
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'pending',
              description: 'Checking for team approval',
              context: 'pr-approval-check'
            });
      - name: Determine PR Number
        id: build
        run: |
          echo "PR: ${{ github.event.pull_request.number }}"
          echo "${{ github.event.pull_request.number }}" > prnum.txt

      - name: Submit
        uses: actions/upload-artifact@v5
        with:
          name: prnum
          path: prnum.txt
          retention-days: 1

