name: "Receive PR 2"

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]

permissions:
  contents: read

jobs:
  noop:
    name: Baseline check
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the required check."
      - id: stuff
        name: Extract PR from workflow_run payload or Github REST API
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context)
