name: "Receive PR 2"

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]

permissions:
  contents: read

jobs:
  prnum:
    name: Baseline check
    runs-on: ubuntu-latest
    steps:
      - name: Determine PR Number
        id: build
        run: |
          echo "PR: ${{ github.event.pull_request.number }}"
          echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Submit
        uses: actions/upload-artifact@v4
        with:
          name: prnum
          path: prnum.txt
          retention-days: 1

